Develop merge 149022
tapdata/tapdata pull request #1423
Opened 2023-10-23 11:37 UTC by ply0011

当共享挖掘任务删除重建后，会导致增量无法进行

2023-10-23 11:39 UTC, jackin-code approved these changes

2023-10-24 02:21 UTC, xbsura requested changes

2023-10-24 02:21 UTC, xbsura commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastTargetPdkShareCDCNode.java
> +			String sign = ShareCdcTableMappingDto.genSign(connectionId, split[split.length - 1]);
here has a bug, I'm not sure whether we should solve it now, mongodb allow table name has dot in it, such as: a.b, b.b, this will make data error

2023-10-24 02:41 UTC, xbsura commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastTargetPdkShareCDCNode.java
> +			String sign = ShareCdcTableMappingDto.genSign(connectionId, split[split.length - 1]);
I create a issue: https://tapdata.coding.net/p/tapdata/bug-tracking/issues/149111/detail

2023-10-24 02:41 UTC, xbsura approved these changes

2023-10-24 06:41 UTC, merged