fix: #6196 【V3.1】JS试运行，数据源连接测试正常，但是试运行JS报错：Can not get data from sour…
tapdata/tapdata pull request #1454
Opened 2023-10-31 02:24 UTC by mnianqi

…ce, Please ensure if source connection is valid

Closes #149123

2023-10-31 02:50 UTC, ply0011 requested changes
参考：https://github.com/tapdata/tapdata/pull/1453

2023-11-03 12:26 UTC, mnianqi commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSampleSourcePdkDataNode.java
源节点没有数据时mock数据并打印日志

2023-11-03 12:32 UTC, mnianqi commented on iengine/modules/observable-module/src/main/java/io/tapdata/observable/logging/appender/ScriptNodeProcessNodeAppender.java
通过过滤jsnodeId，只打印了js节点的日志，需要加上源节点的nodeId

2023-11-03 12:33 UTC, mnianqi commented on manager/tm/src/main/java/com/tapdata/tm/task/controller/TaskController.java
tm这里可以去掉

2023-11-08 02:18 UTC, ply0011 approved these changes

2023-11-08 06:43 UTC, jackin-code approved these changes

2023-11-08 06:43 UTC, merged