Feat event data filter dev
tapdata/tapdata pull request #1458
Opened 2023-11-01 04:16 UTC by 11000100111010101100111

2023-11-01 07:58 UTC, ply0011 requested changes

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/filter/FilterUtil.java
> +        if (null == fieldNames) fieldNames = new HashSet<>();
如果没有字段，是否应该警告或者报错，而不是把所有数据都过滤

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/filter/TargetTableDataEventFilter.java
> +    List<TapEventHandel> handelList = new CopyOnWriteArrayList<>();
handelList -> handleList

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/filter/TargetTableDataEventFilter.java
> +    public void addFilter(TapEventHandel tapEventPredicate) {
这里建议就不叫predicate了，是filter或者handler

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/filter/TargetTableDataEventFilter.java
> +    public <E extends TapdataEvent> TapdataEvent test(E event) {
方法名改为handle

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/filter/TargetTableDataEventFilter.java
> +        for (TapEventHandel handel : handelList) {
handel->handle

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +							obsLogger.debug("Processor base context is empty");
这里是否应该使用debug？或者检查应该前置

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +							obsLogger.debug("TaskDto is empty");
同上

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +							obsLogger.debug("Tap table map is empty");
同上

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +			obsLogger.info("Before the event is output to the target from source, it will automatically block field changes generated by ddl");
建议不用每条数据都打印这条info日志

2023-11-01 07:58 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +					obsLogger.warn("Fail to automatically block new fields, message: {}", exception.getMessage(), exception.getCause());
是否应该直接报错，没有正确过滤，任务应该报错停止

2023-11-01 08:55 UTC, ply0011 requested changes

2023-11-01 08:55 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +		if (Boolean.TRUE.equals(processorBaseContext.getTaskDto().getNeedFilterEventData())) {
这里拿到的needFilterEventData可能不是准确的，source和target是异步初始化的

2023-11-03 10:01 UTC, ply0011 approved these changes

2023-11-06 06:12 UTC, jackin-code approved these changes

2023-11-06 06:12 UTC, merged