fix: type cast error
tapdata/tapdata pull request #1468
Opened 2023-11-05 20:22 UTC by ljvv7

2023-11-06 03:33 UTC, ply0011 requested changes

2023-11-06 03:33 UTC, ply0011 commented on iengine/iengine-common/src/main/java/com/tapdata/processor/FieldProcessUtil.java
> +				if (value instanceof String) {
需要补充单元测试

2023-11-06 08:02 UTC, ljvv7 commented on iengine/iengine-common/src/main/java/com/tapdata/processor/FieldProcessUtil.java
> +				if (value instanceof String) {
好的

2023-11-07 02:50 UTC, ply0011 requested changes

2023-11-07 02:50 UTC, ply0011 commented on iengine/iengine-common/src/test/java/com/tapdata/processor/FieldProcessUtilTest.java
> +    }
空字符串会有什么表现？

2023-11-07 02:50 UTC, ply0011 commented on iengine/iengine-common/src/test/java/com/tapdata/processor/FieldProcessUtilTest.java
> +    @Test(expected = RuntimeException.class)
期望与注释不一致

2023-11-07 02:50 UTC, ply0011 commented on iengine/iengine-common/src/main/java/com/tapdata/processor/FieldProcessUtil.java
> +				}
提供更好的异常信息，例如：日期类型转换失败，字段名：xxx，原始类型: String，原始值：xxx

2023-11-08 02:13 UTC, ply0011 approved these changes

2023-11-08 02:15 UTC, jackin-code approved these changes

2023-11-08 02:15 UTC, merged