fix:JS试运行 标准js和增强js节点日志过滤
tapdata/tapdata pull request #1476
Opened 2023-11-07 03:11 UTC by mnianqi

2023-11-07 03:16 UTC, ply0011 requested changes

2023-11-07 03:16 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSampleSourcePdkDataNode.java
> +						obsLogger.warn("mock data failed");
错误原因输出一下

2023-11-07 03:16 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/controller/TaskController.java
> +        if (logs instanceof JSONArray){
这块封装一下，并增加单测

2023-11-08 02:13 UTC, ply0011 approved these changes

2023-11-08 02:19 UTC, jackin-code approved these changes

2023-11-08 06:42 UTC, merged