Fix thread group util sonarqube develop
tapdata/tapdata pull request #1485
Opened 2023-11-09 09:47 UTC by 11000100111010101100111

（1）http://16.162.191.231:9000/project/issues?id=tapdata&open=AYtCD3PYXYb5O8peM4uR&resolved=false&types=BUG
------- e410a99a0bbde711beae64066651758c56fefcf0

（2）http://16.162.191.231:9000/project/issues?id=tapdata&open=AYtCD3PYXYb5O8peM4uW&resolved=false&types=BUG
------- 607c1253df10c792b83214594aeabf0389e98fc9

2023-11-10 02:58 UTC, ply0011 requested changes

2023-11-10 02:58 UTC, ply0011 commented on iengine/iengine-app/src/main/test/io/tapdata/threadgroup/utils/ThreadGroupUtilTest.java
> +    public void testGroupThreadGroup() {
1. 测试用例过于复杂，可以简化，此处测试ThreadGroupUtil，可以不用mock taskDto与dataProcessorContext，简化每个单测的流程
2. 单测场景太少，补充各种边界异常情况的用例
3. 每个用例需要注释说明

2023-11-10 07:34 UTC, 11000100111010101100111 commented on iengine/iengine-app/src/main/test/io/tapdata/threadgroup/utils/ThreadGroupUtilTest.java
> +    public void testGroupThreadGroup() {
这些用例有点特殊，感觉不mock taskDto与dataProcessorContext不好写用例

2023-11-13 06:32 UTC, ply0011 approved these changes

2023-11-13 11:17 UTC, jackin-code approved these changes

2023-11-13 11:17 UTC, merged