fix #149215  inspect progress bug
tapdata/tapdata pull request #1505
Opened 2023-11-14 09:09 UTC by ningmeng777

2023-11-15 03:04 UTC, ply0011 requested changes

2023-11-15 03:04 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/inspect/compare/TableRowContentInspectJob.java
> +				.divide(new BigDecimal(current > max ? current + 1 : max), 7, BigDecimal.ROUND_HALF_UP).doubleValue();
尝试使用类似以下的方式
System.out.println(BigDecimal.valueOf(0.999999999999999D).setScale(4, RoundingMode.DOWN));

2023-11-15 03:04 UTC, ply0011 requested changes

2023-11-15 03:04 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/inspect/compare/TableRowContentInspectJob.java
>  	private double getProgress() {
补充单测

2023-11-17 02:55 UTC, ply0011 approved these changes

2023-11-20 02:45 UTC, jackin-code approved these changes

2023-11-20 02:46 UTC, merged