Feat cloud send mail limit develop
tapdata/tapdata pull request #1507
Opened 2023-11-15 02:53 UTC by weiliang110100

2023-11-15 08:31 UTC, ply0011 requested changes

2023-11-15 08:31 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/alarm/service/impl/AlarmServiceImpl.java
> +                if(!settingsService.isCloud() || messageService.checkMessageLimit(userDetail) < MailUtils.CLOUD_MAIL_LIMIT){
1. 这个判断出现多次，是否可以封装一下？
2. CLOUD_MAIL_LIMIT这个常量作为默认值，最好提供一个环境变量的修改入口

2023-11-17 02:53 UTC, ply0011 approved these changes

2023-11-17 02:55 UTC, jackin-code approved these changes

2023-11-17 02:55 UTC, merged