fix(task-retry): when task retry and sign timestamp and not sign befor
tapdata/tapdata pull request #1535
Opened 2023-11-22 12:02 UTC by 11000100111010101100111

2023-11-22 12:32 UTC, ply0011 requested changes

2023-11-22 12:32 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/schedule/TapDataTaskSchedulerUtil.java
> +        return null == retryStartTime || retryStartTime < 0;
这里应该改成retryStartTime <= 0

2023-11-22 14:16 UTC, ply0011 approved these changes

2023-11-23 03:46 UTC, jackin-code approved these changes

2023-11-23 03:46 UTC, merged