fix #150538:After the instance is unsubscribed, the engine is still r…
tapdata/tapdata pull request #1574
Opened 2023-12-08 03:02 UTC by weiliang110100

…unning

2023-12-08 04:17 UTC, ply0011 requested changes

2023-12-08 04:17 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/worker/controller/WorkerController.java
> +                    workerService.sendStopWorkWs(worker.getProcessId(), userDetail);
1. 应该增加退订的判断条件，不然其他operation过来，也会通知停止引擎，就出现问题了
2. 补充单测

2023-12-12 06:56 UTC, ply0011 approved these changes

2023-12-13 03:48 UTC, jackin-code approved these changes

2023-12-13 03:48 UTC, merged