feature: preload schema
tapdata/tapdata pull request #1578
Opened 2023-12-08 11:16 UTC by mnianqi

2023-12-11 02:34 UTC, ply0011 requested changes

2023-12-11 02:34 UTC, ply0011 commented on iengine/iengine-common/src/main/java/io/tapdata/schema/TapTableMap.java
> +		future.join();
join是阻塞的，这里用的不对

2023-12-11 02:34 UTC, ply0011 commented on iengine/iengine-common/src/main/java/io/tapdata/schema/TapTableMap.java
> +		executorService.shutdown();
这里的shutdown可能导致线程内还未完成，就被停止了

2023-12-11 02:34 UTC, ply0011 commented on iengine/iengine-common/src/main/java/io/tapdata/schema/TapTableMap.java
> +		TapLogger.info("[preload-schema-fork-thread]", "preload schema continue");
引擎内不应该使用TapLogger

2023-12-11 02:34 UTC, ply0011 commented on iengine/iengine-common/src/test/java/io/tapdata/schema/TapTableMapTest.java
> +    }
请补充测试同步切换异步的逻辑

2023-12-15 07:45 UTC, ply0011 approved these changes

2023-12-18 10:13 UTC, jackin-code approved these changes

2023-12-18 10:13 UTC, merged