Fix load schema dev gavin
tapdata/tapdata pull request #1592
Opened 2023-12-13 06:56 UTC by 11000100111010101100111

2023-12-14 10:02 UTC, ply0011 requested changes

2023-12-14 10:02 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/Schedule/ConnectorManager.java
>  	public void schemaAutoUpdate() {
删除无用代码

2023-12-14 10:03 UTC, ply0011 approved these changes

2023-12-15 02:14 UTC, 11000100111010101100111 commented on iengine/iengine-app/src/main/java/io/tapdata/Schedule/ConnectorManager.java
>  	public void schemaAutoUpdate() {
[0ea8bb4](https://github.com/tapdata/tapdata/pull/1592/commits/0ea8bb4f14ffba53b2c5a0d81e848461b1c51b92)
这样些已经移除过了

2023-12-15 04:16 UTC, jackin-code approved these changes

2023-12-15 04:16 UTC, merged