Fix release v3.5.8 cron or plan task num
tapdata/tapdata pull request #1597
Opened 2023-12-15 04:29 UTC by ljvv7

2023-12-18 10:26 UTC, ply0011 requested changes

2023-12-18 10:26 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/TaskService.java
> +                    int runningNum = calculationEngineVo.getRunningNum();
太多重复代码，封装一下

2023-12-19 02:29 UTC, ply0011 approved these changes

2023-12-19 02:59 UTC, jackin-code approved these changes

2023-12-19 02:59 UTC, merged