Fix develop cron task limit
tapdata/tapdata pull request #1599
Opened 2023-12-18 02:52 UTC by ljvv7

2023-12-18 10:27 UTC, ply0011 requested changes

2023-12-18 10:27 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/schedule/service/ScheduleService.java
> +        if (taskService.checkIsCronOrPlanTask(taskDto)) {
太多重复代码，封装一下

2023-12-19 02:30 UTC, ply0011 approved these changes

2023-12-19 02:59 UTC, jackin-code approved these changes

2023-12-19 02:59 UTC, merged