Feat limit scheduled task
tapdata/tapdata pull request #1601
Opened 2023-12-19 08:19 UTC by weiliang110100

2023-12-19 11:08 UTC, ply0011 requested changes

2023-12-19 11:08 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/TaskService.java
> +            TaskDto task = findByTaskId(taskId);
只获取需要使用的字段

2023-12-20 08:35 UTC, ply0011 approved these changes

2023-12-20 09:24 UTC, jackin-code approved these changes

2023-12-20 09:24 UTC, merged