fix: circuit breaker recovery bug
tapdata/tapdata pull request #1624
Opened 2024-01-02 10:10 UTC by weiliang110100

2024-01-03 02:32 UTC, ply0011 requested changes

2024-01-03 02:32 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/Settings/constant/SettingUtil.java
> +        return String.valueOf(settingsService.getByCategoryAndKey(category, key));
补充一些空指针防范的代码

2024-01-04 04:07 UTC, ply0011 approved these changes

2024-01-04 06:49 UTC, jackin-code approved these changes

2024-01-04 06:49 UTC, merged