fix(python): print all message info when execute ProcessBuilder shell to avoid process blocking
tapdata/tapdata pull request #1638
Opened 2024-01-09 04:03 UTC by 11000100111010101100111

2024-01-09 06:10 UTC, ply0011 requested changes

2024-01-09 06:10 UTC, ply0011 commented on iengine/modules/observable-module/src/main/java/io/tapdata/observable/metric/py/PythonUtils.java
> +        new Thread(() -> printMsg(stream, logger)).start();
线程设置名称，固定前缀

2024-01-11 02:25 UTC, ply0011 approved these changes

2024-01-11 03:10 UTC, jackin-code approved these changes

2024-01-11 03:11 UTC, merged