Feat cloud add recipient develop
tapdata/tapdata pull request #1708
Opened 2024-02-01 08:43 UTC by weiliang110100

2024-02-02 06:29 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/Settings/service/SettingsService.java
> +                receiverList.get().addAll(alarmMailDto.getEmailAddressList());
receiverList.get().addAll()有可能触发空指针异常

2024-02-02 06:32 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/alarmMail/controller/AlarmMailController.java
> +        UserDetail userDetail = getLoginUser();
如果没拿到userDetail做个防御

2024-02-02 06:37 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/utils/MailUtils.java
> +            sendStatus.setErrorMessage("mail is null");
这里的errorMessage的描述过于简单

2024-02-02 06:38 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/utils/MailUtils.java
> +        }
这块逻辑与下面好像有不少重复，是否可以封装到一起

2024-02-02 06:38 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/utils/MailUtils.java
> +            InternetAddress[] internetAddressList = addressList.toArray(new InternetAddress[notInBlacklistAddress.size()]);
这块逻辑与下面好像有不少重复，是否可以封装到一起

2024-02-02 06:39 UTC, ply0011 approved these changes

2024-02-02 06:40 UTC, ply0011 requested changes
参考留言，有一些需要改动

2024-02-04 07:53 UTC, ply0011 approved these changes

2024-02-04 10:21 UTC, jackin-code approved these changes

2024-02-04 10:21 UTC, merged