fix(engine):share miner support replace event
tapdata/tapdata pull request #1711
Opened 2024-02-02 06:44 UTC by ljvv7

2024-02-02 07:12 UTC, ply0011 commented on iengine/iengine-app/src/test/java/io/tapdata/flow/engine/V2/sharecdc/impl/ShareCdcPDKTaskReaderTest.java
> +                Assert.assertEquals(CLAIMID,tapUpdateRecordEvent.getAfter().get("CLAIM_ID"));
换成Assertions，junit5的断言，Assert是junit4的，最好别混用，这个类其他的断言也统一修改一下

2024-02-02 07:12 UTC, ply0011 commented on iengine/iengine-common/src/main/java/io/tapdata/flow/engine/V2/util/TapEventUtil.java
> +		return null;
这里返回null是否合适

2024-02-02 07:17 UTC, ljvv7 commented on iengine/iengine-app/src/test/java/io/tapdata/flow/engine/V2/sharecdc/impl/ShareCdcPDKTaskReaderTest.java
> +                Assert.assertEquals(CLAIMID,tapUpdateRecordEvent.getAfter().get("CLAIM_ID"));
好的

2024-02-02 07:18 UTC, ply0011 requested changes
参考留言修改

2024-02-04 07:51 UTC, ply0011 requested changes
TapEventUtilTest的断言也换成junit

2024-02-04 08:44 UTC, ply0011 approved these changes

2024-02-04 10:21 UTC, jackin-code approved these changes

2024-02-04 10:21 UTC, merged