Feat develop retry flag
tapdata/tapdata pull request #1734
Opened 2024-02-21 08:53 UTC by ljvv7

2024-02-27 02:48 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastPdkBaseNode.java
>  		Long maxRetryTimeSecond = taskConfig.getTaskRetryConfig().getMaxRetryTime(TimeUnit.SECONDS);
这行在当前逻辑应该是没用的，直接Long maxRetryTimeSecond=DEFAULT_RETRY_PERIOD_SECONDS

2024-02-27 02:50 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastPdkBaseNode.java
> +	public static final long DEFAULT_FUNCTION_RETRY_TIME_SECOND = 900L;
这个常量封装到重试模块中，放在此处后续复用会比较麻烦

2024-02-27 02:52 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/TaskService.java
> -                .unset("functionRetryEx")
这里没必要删掉，旧数据在重置的时候可以通过这里，删掉旧的无用字段

2024-02-27 02:52 UTC, ply0011 requested changes
根据备注修改

2024-02-27 02:53 UTC, ljvv7 commented
> 根据备注修改

好的

2024-03-07 09:20 UTC, ply0011 requested changes

2024-03-07 09:20 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/task/retry/task/TaskRetryFactory.java
> +		synchronized (taskRetryServiceMap) {
1. 不需要用到同步锁，增加了锁粒度，降低性能；
2. 此处不需要考虑二次调用变更的需求

2024-03-07 09:20 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/task/retry/task/TaskRetryFactory.java
> +		synchronized (taskRetryServiceMap) {
```suggestion
		synchronized (taskRetryServiceMap) {
```
建议完全还原之前的代码即可

2024-03-07 09:20 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/task/retry/task/TaskRetryService.java
> +	public static final long DEFAULT_FUNCTION_RETRY_TIME_SECOND = 900L;
这里建议使用TimeUnit

2024-03-07 09:20 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/task/retry/task/TaskRetryService.java
> +	public static final long DEFAULT_FUNCTION_RETRY_TIME_SECOND = 900L;
```suggestion
    // 改为
    public static final long DEFAULT_FUNCTION_RETRY_TIME_SECOND = TimeUnit.MINUTES.toSeconds(15L);
```

2024-03-07 09:22 UTC, ljvv7 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/task/retry/task/TaskRetryFactory.java
> +		synchronized (taskRetryServiceMap) {
好的

2024-03-11 02:54 UTC, closed without merging