fix: refresh pdk connector jar when exists file but not complete
tapdata/tapdata pull request #1743
Opened 2024-02-28 07:07 UTC by mnianqi

Closes #151194

2024-02-28 10:25 UTC, ply0011 commented on iengine/iengine-common/src/main/java/io/tapdata/flow/engine/V2/util/PdkUtil.java
> +			e.printStackTrace();
这行删掉

2024-02-28 10:39 UTC, ply0011 requested changes
整体的完整性检查逻辑有漏洞，需要重新修改

2024-03-11 04:20 UTC, ply0011 requested changes

2024-03-11 04:20 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/ds/service/impl/PkdSourceService.java
> +				inputStreamToFile(ins,file);
加个判断
- 如果本地文件存在，则不用写入本地文件
- 如果文件不存在，则写入本地文件，获取到md5后清理本地文件

2024-03-11 04:20 UTC, ply0011 commented on iengine/iengine-common/src/main/java/io/tapdata/flow/engine/V2/util/PdkUtil.java
> +				reDownloadIfNeed(httpClientMongoOperator,pdkHash,fileName,theFilePath,resourceId,callback);
改进成循环的方式进行重试

2024-03-18 04:28 UTC, ply0011 requested changes

2024-03-18 04:28 UTC, ply0011 commented on iengine/iengine-common/src/main/java/io/tapdata/flow/engine/V2/util/PdkUtil.java
> +				while (needDownload) {
重试循环需要增加一个退出逻辑，这里可以是连续3次失败则报错退出

2024-03-18 04:28 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/ds/service/impl/PkdSourceService.java
> +				}
上面一整块建议封装到getFileMD5方法中

2024-03-22 08:52 UTC, ply0011 approved these changes

2024-03-25 03:37 UTC, jackin-code approved these changes

2024-03-25 03:38 UTC, merged