feat(custom-field-verify): #151275 Data validation supports automatic value updates for filtering conditions(release3.5.1)
tapdata/tapdata pull request #1775
Opened 2024-03-21 02:38 UTC by 11000100111010101100111

2024-03-21 06:48 UTC, ply0011 requested changes

2024-03-21 06:48 UTC, ply0011 commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +    public static final String FUNCTION_NAME = "$dynamicDate";
类名称与该常量一致，统一改为DynamicDate
```suggestion
public class DynamicDate implements CustomSQLObject<Object, Map<String, Object>> {
    public static final String FUNCTION_NAME = "$dynamicDate";
```

2024-03-21 07:17 UTC, HarsenLin commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +                }
转换失败时，直接抛错。如果错误被吞，会导致结果与用户预期不一致，且无法知道原因。
```suggestion
                subtract = Long.parseLong(String.valueOf(sub));
```

2024-03-21 07:33 UTC, HarsenLin commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +        }
转换失败时，直接抛错。如果错误被吞，会导致结果与用户预期不一致，且无法知道原因。
抛
```suggestion
        if (functionObj instanceof Map) {
            Map<String, Object> functionMap = (Map<String, Object>) functionObj;
            filter = functionMap.get(FORMAT);
            toString = Boolean.TRUE.equals(functionMap.get(TO_STRING));
            Object sub = functionMap.get(SUBTRACT);
            if (sub instanceof Number) {
                subtract = ((Number)sub).longValue();
            } else if (null != sub) {
                throw new IllegalArgumentException("Decode '" + DYNAMIC_DATE + "' failed, '" + SUBTRACT + "' must be number: " + sub);
            }
        }
        if (null == filter) {
            throw new IllegalArgumentException("Decode '" + DYNAMIC_DATE + "' failed, '" + SUBTRACT + "' is required.");
        }
```

2024-03-21 07:37 UTC, HarsenLin commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +        return covert(new Date(dateTime), subtract);
如果我需要过滤 1900 的数据也不支持吗？Date 是能够表示的

2024-03-21 07:40 UTC, HarsenLin commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +        dateTime = replaceDate(dateTime);
最好不要用这个工具类，性能超差，这里的功能比较明确，可以自己直接构造。请将 DateUtil 移除

2024-03-21 07:48 UTC, 11000100111010101100111 commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +        dateTime = replaceDate(dateTime);
自己构造会有bug的风险，这种性能在校验任务里应该可以接受的了

2024-03-21 07:49 UTC, HarsenLin commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +        return format;
时间操作参考代码：

Calendar calendar = Calendar.getInstance();
calendar.add(Calendar.MILLISECOND, -10*60*1000); // 减10分钟

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:00");
sdf.setTimeZone(TimeZone.getTimeZone(ZoneId.of("+08:00"))); // 如对时区有要求，可以加上这个配置
String dateFormatStr = sdf.format(calendar.getTime());
System.out.println(dateFormatStr);

2024-03-21 07:53 UTC, 11000100111010101100111 commented on connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/decoder/impl/AutoUpdateDateFilterTime.java
> +        return format;
可以查看calculateDate()方法，我也是这样实现的

2024-03-21 11:38 UTC, HarsenLin approved these changes

2024-03-22 08:52 UTC, ply0011 approved these changes

2024-03-22 08:53 UTC, merged