feat: Index Sync - Engine
tapdata/tapdata pull request #1795
Opened 2024-03-27 11:01 UTC by mnianqi

Closes TAP-1491

2024-03-28 06:27 UTC, ply0011 requested changes

2024-03-28 06:27 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastTargetPdkDataNode.java
> +		}
结束增加日志，统计一下耗时等信息

2024-03-29 02:52 UTC, ply0011 requested changes
1. 日志首字母大写
2. 索引分开创建，分开输出日志信息

2024-03-29 09:46 UTC, ply0011 approved these changes

2024-03-31 15:47 UTC, jackin-code approved these changes

2024-03-31 15:47 UTC, merged