feat:TAP-1514 Support skipping the previous error when starting the t…
tapdata/tapdata pull request #1809
Opened 2024-04-01 11:08 UTC by weiliang110100

…ask, pop-up window to view the error, select the error to skip

2024-04-02 06:29 UTC, ply0011 requested changes

2024-04-02 06:29 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/HazelcastBaseNode.java
> +		SkipError skipError = SkipErrorStrategy.getSkipErrorStrategy(null).getSkipError();
最好别写这种传入null的，阅读性比较差，可以加一个getDefaultSkipErrorStrategy()的方法
```suggestion
		SkipError skipError = SkipErrorStrategy.getDefaultSkipErrorStrategy().getSkipError();
```

2024-04-02 06:29 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/HazelcastBaseNode.java
> +				clientMongoOperator.insertOne(errorEvents,ConnectorConstant.TASK_COLLECTION + "/errorEvents/" + taskDto.getId());
1. 两部分代码做一下封装
2. 异常跳过逻辑出错不影响正常流程
    - 不能覆盖原本的异常
    - 不影响原本的任务异常停止
    - 跳过逻辑的错误，可以通过wanring输出

2024-04-02 06:29 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/HazelcastBaseNode.java
> +				obsLogger.warn(errorMessage + "; Will skip it");
这里改为info级别，并用固定的前缀方便以后排查
```suggestion
				obsLogger.info("The current exception match the skip exception strategy"+errorMessage);
```

2024-04-02 06:29 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/task/skipError/ErrorMessageSkip.java
> +        String message = errorEvent.getMessage();
message是否有可能为空

2024-04-02 06:29 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/HazelcastBaseNode.java
> +		}
跳过后是否需要从中间库删掉该数据，取决于需求，是跳过一次还是只要不重置，都跳过，可以与产品确认一下

2024-04-08 06:46 UTC, ply0011 approved these changes

2024-04-08 10:18 UTC, jackin-code approved these changes

2024-04-08 10:18 UTC, merged