Tap 1497 replication table breakpoint dev
tapdata/tapdata pull request #1845
Opened 2024-04-15 06:56 UTC by 11000100111010101100111

2024-04-16 04:13 UTC, ply0011 requested changes

2024-04-16 04:13 UTC, ply0011 commented on iengine/iengine-common/src/main/java/com/tapdata/entity/dataflow/SyncProgress.java
> +	public boolean batchIsOverOfTable(String tableId) {
带逻辑的方法建议新建一个util，不应放在实体类

2024-04-16 04:13 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +						initBatchOffset(newTables);
这里不应调用init方法
```suggestion
						syncProgress.updateBatchOffset(id, null, TableBatchReadStatus.RUNNING.name())
```

2024-04-16 04:13 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkBaseNode.java
> +					Map<String, Object> batchOffsetObj = (Map<String, Object>) syncProgress.putIfAbsentBatchOffsetObj();
这里不需要修改

2024-04-18 04:39 UTC, ply0011 approved these changes

2024-04-18 05:57 UTC, jackin-code approved these changes

2024-04-18 08:06 UTC, jackin-code commented
exception case: sonarq's bug.

2024-04-18 08:06 UTC, merged