Feat(TAP-2016): The data replication task list needs to add a field to display the milestone stage of the current task.
tapdata/tapdata pull request #1871
Opened 2024-04-22 09:27 UTC by 11000100111010101100111

2024-04-23 12:21 UTC, ply0011 requested changes
重置任务是否需要重置同步状态？没有看到相应的代码

2024-04-23 12:21 UTC, ply0011 commented on iengine/modules/milestone-module/pom.xml
> +        </dependency>
这个依赖在哪里用到了？

2024-04-23 12:21 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/behavior/aop/BehaviorAop.java
> +import com.tapdata.tm.task.constant.SyncStatus;
如果没有用到的话，就不保留了

2024-04-23 12:21 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/controller/TaskController.java
> +				task.setSyncStatus(SyncStatus.NORMAL);
这里是否是修改任务重置同步状态，是的话，是不是编辑任务不应该重置

2024-04-23 12:21 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/controller/TaskController.java
> +                task.setSyncStatus(SyncStatus.NORMAL);
这里是否是修改任务重置同步状态，是的话，是不是编辑任务不应该重置

2024-04-23 12:21 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/impl/TaskNodeServiceImpl.java
> +        taskDtoCopy.setSyncStatus(SyncStatus.NORMAL);
这里是否是试运行js会重置同步状态？感觉试运行应该保持状态

2024-04-23 12:21 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/impl/TaskNodeServiceImpl.java
> +        taskDtoCopy.setSyncStatus(SyncStatus.NORMAL);
同上

2024-04-24 03:34 UTC, 11000100111010101100111 commented on manager/tm/src/main/java/com/tapdata/tm/task/controller/TaskController.java
> +				task.setSyncStatus(SyncStatus.NORMAL);
需要重置，任务状态都变了，这个这个同步状态是在running的时候展示的，任务不是running，这个状态不情况有冲突

2024-04-24 03:34 UTC, 11000100111010101100111 commented on manager/tm/src/main/java/com/tapdata/tm/task/controller/TaskController.java
> +                task.setSyncStatus(SyncStatus.NORMAL);
需要重置，任务状态都变了，这个这个同步状态是在running的时候展示的，任务不是running，这个状态不情况有冲突

2024-04-24 03:34 UTC, 11000100111010101100111 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/impl/TaskNodeServiceImpl.java
> +        taskDtoCopy.setSyncStatus(SyncStatus.NORMAL);
需要重置，任务状态都变了，这个这个同步状态是在running的时候展示的，任务不是running，这个状态不情况有冲突

2024-04-24 03:34 UTC, 11000100111010101100111 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/impl/TaskNodeServiceImpl.java
> +        taskDtoCopy.setSyncStatus(SyncStatus.NORMAL);
需要重置，任务状态都变了，这个这个同步状态是在running的时候展示的，任务不是running，这个状态不情况有冲突

2024-04-26 06:42 UTC, ply0011 approved these changes

2024-04-28 07:20 UTC, jackin-code approved these changes

2024-04-28 07:20 UTC, merged