Tap 2285 provides a separate interface for modifying alarm settings to prevent adjustment of alarm settings from affecting task settings
tapdata/tapdata pull request #1877
Opened 2024-04-25 07:54 UTC by weiliang110100

2024-04-26 06:36 UTC, ply0011 requested changes
1. 完善jira子任务状态
2. 补充自测场景

2024-04-26 07:50 UTC, weiliang110100 commented
https://tapdata.atlassian.net/jira/software/c/projects/TAP/boards/4/backlog?selectedIssue=TAP-2285 已补充

2024-04-26 08:54 UTC, ply0011 commented
这个功能可能还需要测一下开源场景下的表现，期望是跟之前一样，不能生效并提示该功能无法使用

2024-04-26 10:40 UTC, weiliang110100 commented
https://tapdata.atlassian.net/jira/software/c/projects/TAP/boards/4/backlog?selectedIssue=TAP-2285 已补充

2024-04-28 03:13 UTC, ply0011 requested changes

2024-04-28 03:13 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/controller/TaskController.java
> +import com.tapdata.tm.commons.task.dto.alarm.AlarmVO;
确认下是否需要优化引用

2024-04-28 03:13 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/TaskServiceImpl.java
> +import com.tapdata.tm.commons.task.dto.alarm.AlarmVO;
确认下是否需要优化引用

2024-04-28 03:13 UTC, ply0011 commented on manager/tm/src/test/java/com/tapdata/tm/task/service/TaskServiceImplTest.java
> +import org.springframework.data.mongodb.core.query.Update;
确认下是否需要优化引用

2024-04-28 06:50 UTC, ply0011 approved these changes

2024-04-28 07:20 UTC, jackin-code approved these changes

2024-04-28 07:20 UTC, merged