TAP-2015-The-full-synchronization-details-page-of-the-replication-tas…
tapdata/tapdata pull request #1879
Opened 2024-04-25 15:20 UTC by weiliang110100

…k-needs-to-support-searching-for-tables-based-on-table-names

2024-04-26 06:31 UTC, ply0011 requested changes
希望在jira中补充自测的场景用例

2024-04-29 07:42 UTC, weiliang110100 commented
https://tapdata.atlassian.net/jira/software/c/projects/TAP/boards/4/backlog?assignee=712020%3A992b5518-90aa-4906-97e7-65329738df91&selectedIssue=TAP-2015

2024-04-29 08:02 UTC, ply0011 approved these changes

2024-04-29 09:59 UTC, jackin-code approved these changes

2024-04-29 09:59 UTC, merged