Fix tap 2436 sqlexecute error develop
tapdata/tapdata pull request #1899
Opened 2024-05-06 10:22 UTC by ningmeng777

2024-05-06 10:32 UTC, ply0011 requested changes
合并dev分支，jira中需要在卡片中补充自测截图

2024-05-06 10:42 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-TAP-2436-sqlexecute-error-develop&id=tapdata

2024-05-07 02:23 UTC, ply0011 approved these changes

2024-05-07 08:49 UTC, jackin-code approved these changes

2024-05-07 08:53 UTC, xbsura approved these changes
OK For me

2024-05-07 08:54 UTC, merged