feat: tm unit test
tapdata/tapdata pull request #1901
Opened 2024-05-06 10:52 UTC by mnianqi

Closes TAP-2344

2024-05-10 03:40 UTC, ply0011 requested changes
有3处单测有报错，但是单测又通过了，需要看一下

2024-05-10 03:40 UTC, ply0011 commented on manager/tm/src/test/java/com/tapdata/tm/metadatainstance/service/MetadataInstancesServiceImplTest.java
> +				Map<String, TapType> actual = metadataInstancesService.dataType2TapType(dto, userDetail);
这里运行控制台有报错，看一下什么原因，为什么报错单测还能通过

2024-05-10 03:40 UTC, ply0011 commented on manager/tm/src/test/java/com/tapdata/tm/task/service/TaskServiceImplTest.java
> +            List<MutiResponseMessage> responseMessages = taskService.batchRenew(taskIds, user, request, response);
运行有报错

2024-05-10 03:40 UTC, ply0011 commented on manager/tm/src/test/java/com/tapdata/tm/task/service/TaskServiceImplTest.java
> +            List<MutiResponseMessage> responseMessages = taskService.batchStop(taskIds, user, request, response);
运行有报错

2024-05-11 06:29 UTC, mnianqi commented on manager/tm/src/test/java/com/tapdata/tm/metadatainstance/service/MetadataInstancesServiceImplTest.java
> +				Map<String, TapType> actual = metadataInstancesService.dataType2TapType(dto, userDetail);
mock InstanceFactory的instance方法之后无报错信息

2024-05-11 06:29 UTC, mnianqi commented on manager/tm/src/test/java/com/tapdata/tm/task/service/TaskServiceImplTest.java
> +            List<MutiResponseMessage> responseMessages = taskService.batchRenew(taskIds, user, request, response);
预期抛出异常，日志打印异常信息

2024-05-11 06:29 UTC, mnianqi commented on manager/tm/src/test/java/com/tapdata/tm/task/service/TaskServiceImplTest.java
> +            List<MutiResponseMessage> responseMessages = taskService.batchStop(taskIds, user, request, response);
预期抛出异常，日志打印异常信息

2024-05-13 07:07 UTC, ply0011 approved these changes

2024-05-13 11:06 UTC, merged