fix(tm): Handling the problem of slow access speed to the testing env…
tapdata/tapdata pull request #1902
Opened 2024-05-06 13:07 UTC by ply0011

…ironment

Creating indexes during tm initialization to solve this problem

Closes TAP-2468

2024-05-06 13:08 UTC, jackin-code approved these changes

2024-05-06 13:15 UTC, xbsura requested changes
db.fs.chunks.createIndex( { files_id: 1, n: 1 }, { unique: true } );

2024-05-06 13:24 UTC, xbsura commented
for mongodb, gridfs will use files_id to do query, and use n to do sort, so { files_id: 1, n: 1 } is a better choice, and this is in mongodb document: https://www.mongodb.com/zh-cn/docs/v6.0/core/gridfs/

and also, please create index in fs.files: db.fs.files.createIndex( { filename: 1, uploadDate: 1 } );

2024-05-07 02:57 UTC, ply0011 commented
MongoDB Driver will create indexs on fs.chunks, but on dev environment, this index is missing. Suspect it was manual deleted. When attempting to rebuild, a duplicate index error occurs. Close this pr is the final decision.

2024-05-07 02:58 UTC, closed without merging