Tap 1091 mongo db sql class database feature optimization
tapdata/tapdata pull request #1904
Opened 2024-05-08 07:58 UTC by 11000100111010101100111

2024-05-08 08:22 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **2.2222222222222223**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-1091-MongoDB-SQL-class-database-feature-optimization&id=tapdata

2024-05-09 03:37 UTC, ply0011 requested changes
iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/HazelcastSchemaTargetNode.java
这里面，对于试运行后的数据，需要增加深度遍历的逻辑，可以在最大程度保证所有子字段不会缺失

2024-05-09 12:41 UTC, ply0011 approved these changes

2024-05-10 11:21 UTC, jackin-code approved these changes

2024-05-10 11:21 UTC, merged