Tap 2103 dynamic target table name
tapdata/tapdata pull request #1906
Opened 2024-05-09 07:58 UTC by 11000100111010101100111

2024-05-09 08:22 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **52.317880794701985**
- Status: **ERROR**, MetricKey: **new_blocker_violations**, ActualValue: **1**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2103-dynamic-Target-table-name&id=tapdata

2024-05-10 03:13 UTC, ply0011 requested changes

2024-05-10 03:13 UTC, ply0011 commented on manager/tm-common/src/main/java/com/tapdata/tm/error/TapDynamicTableNameExCode_1.java
> +public interface TapDynamicTableNameExCode_1 {
类名改为TapDynamicTableNameExCode_35，同时TapHashInspectExCode_1也一起改一下TapHashInspectExCode_34

2024-05-10 03:19 UTC, ply0011 commented
另外：自测截图需要补充在jira

2024-05-10 05:59 UTC, 11000100111010101100111 commented on manager/tm-common/src/main/java/com/tapdata/tm/error/TapDynamicTableNameExCode_1.java
> +public interface TapDynamicTableNameExCode_1 {
TapHashInspectExCode_1的修改在闭源仓库：
https://github.com/tapdata/tapdata-enterprise/pull/252

2024-05-10 06:25 UTC, ply0011 approved these changes

2024-05-10 11:20 UTC, jackin-code approved these changes

2024-05-10 11:20 UTC, merged