feat: TAP-2081 Adding user data reporting functionality to the open-s…
tapdata/tapdata pull request #1936
Opened 2024-05-24 10:20 UTC by mnianqi

…ource version.

2024-05-24 10:49 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2081-user-data-reporting-oss&id=tapdata

2024-05-28 03:08 UTC, ply0011 requested changes

2024-05-28 03:08 UTC, ply0011 commented on manager/tm/src/test/java/com/tapdata/tm/report/service/UserDataReportServiceTest.java
> +            verify(userDataReportService,never()).consumeData(any(Object.class));
1. 不要sleep
2. 这个断言不太好

2024-05-28 10:15 UTC, ply0011 requested changes

2024-05-28 10:15 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/report/service/platform/GoogleAnalyticsPlatform.java
> +    public static final String CONNECT_TIMEOUT = System.getenv().getOrDefault("GOOGLE_CLIENT_CONNECT_TIMEOUT","5000");
建议使用spring的配置文件，与下面的风格统一

2024-05-28 10:15 UTC, ply0011 commented on manager/tm/src/test/java/com/tapdata/tm/report/service/UserDataReportServiceTest.java
> +            assertNull(poll);
断言校验一些初始化的信息是否正确，不需要对这个reportQueue进行断言

2024-05-29 02:48 UTC, ply0011 approved these changes

2024-05-29 02:48 UTC, merged