Tap 2472 the count filter conditions of advanced queries
tapdata/tapdata pull request #1944
Opened 2024-05-28 05:45 UTC by ningmeng777

2024-05-28 10:20 UTC, ply0011 requested changes

2024-05-28 10:20 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkDataNode.java
> +								counts.set(countByPartitionFilterFunction.countByPartitionFilter(connectorNode.getConnectorContext(), table, tapAdvanceFilter));
是否需要判断countByPartitionFilterFunction是否为空

2024-05-28 10:36 UTC, ningmeng777 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkDataNode.java
> +								counts.set(countByPartitionFilterFunction.countByPartitionFilter(connectorNode.getConnectorContext(), table, tapAdvanceFilter));
这个不需要判断了。现在都加了这个方法。

2024-05-29 01:47 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **66.66666666666667**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2472-The-count-filter-conditions-of-advanced-queries&id=tapdata

2024-05-29 03:29 UTC, ply0011 requested changes

2024-05-29 03:29 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkDataNode.java
> +									throw new TapCodeException(TaskProcessorExCode_11.SOURCE_NOT_SUPPORT_COUNT_BY_PARTITION_FILTER_FUNCTION,
我建议如果是CountByPartitionFilterFunction没支持，先尝试原有的逻辑（调用: batchCountFunction），如果batchCountFunction没有，则也是打印warning，因为无法count导致无法同步数据是不太好的

2024-05-29 03:30 UTC, ningmeng777 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/pdk/HazelcastSourcePdkDataNode.java
> +									throw new TapCodeException(TaskProcessorExCode_11.SOURCE_NOT_SUPPORT_COUNT_BY_PARTITION_FILTER_FUNCTION,
好的 我按照你说的在修复下

2024-05-29 11:57 UTC, ply0011 approved these changes

2024-05-29 11:57 UTC, merged