fix: TAP-2921 AccessToken table not set TTL, make it huge when system…
tapdata/tapdata pull request #1969
Opened 2024-06-04 07:37 UTC by mnianqi

… running for long time

2024-06-04 10:02 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2921-AccessToken-TTL&id=tapdata

2024-06-05 10:37 UTC, ply0011 requested changes

2024-06-05 10:37 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/init/patches/daas/v3_8_1_AccessToken_TTL_Index.java
> +        yaml.setResources(new ClassPathResource("application-default.yml"));
不能这样写，正式运行的环境，可能是外部的配置文件

2024-06-05 10:37 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/init/patches/daas/v3_8_1_AccessToken_TTL_Index.java
> +        long buffer = 86400L;
建议改成TimeUnit的写法
TimeUnit.DAYS.toMillis(1L)

2024-06-06 02:54 UTC, ply0011 approved these changes

2024-06-06 02:54 UTC, merged