fix: fix sonar blocker and critical bug
tapdata/tapdata pull request #2009
Opened 2024-06-17 08:44 UTC by mnianqi

2024-06-17 09:08 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **42.10526315789474**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-24 11:13 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **1**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-25 02:47 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **1**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-25 03:33 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-26 03:12 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-26 08:53 UTC, ply0011 requested changes

2024-06-26 08:53 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/data/HazelcastSchemaTargetNode.java
> -						} catch (Exception e) {
改为warn级别的日志输出

2024-06-26 08:53 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/task/TapdataTaskScheduler.java
> +			if (Thread.currentThread().isInterrupted()){
这个main方法删除

2024-06-26 08:53 UTC, ply0011 commented on iengine/modules/proxy-client-module/src/main/java/io/tapdata/proxy/client/ProxySubscriptionManager.java
> +	public synchronized void startIMClient(List<String> baseURLs, String accessToken) {
最好别在方法上锁

2024-06-26 08:53 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/inspect/InspectFactory.java
> +    public static synchronized InspectService getInstance(ClientMongoOperator clientMongoOperator, SettingService settingService) throws ClassNotFoundException, NoSuchMethodException, InvocationTarge
最好别在方法上锁

2024-06-26 09:24 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-26 10:38 UTC, ply0011 approved these changes

2024-06-26 10:39 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-26 11:04 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-26 11:47 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-develop-sonar-bug&id=tapdata

2024-06-26 16:24 UTC, ply0011 commented
# exception case

This is fix issues in the old code identified by the Sonar scan. It is agreed that unit tests are not required

2024-06-26 16:24 UTC, merged