Harsen/tap 2360 develop auto recovery
tapdata/tapdata pull request #2012
Opened 2024-06-17 10:41 UTC by HarsenLin

2024-06-17 11:10 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_blocker_violations**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **57**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-2360-develop-AutoRecovery&id=tapdata

2024-06-17 11:39 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_blocker_violations**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **57**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-2360-develop-AutoRecovery&id=tapdata

2024-06-19 07:23 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-2360-develop-AutoRecovery&id=tapdata

2024-06-21 06:29 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **57.77777777777778**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-2360-develop-AutoRecovery&id=tapdata

2024-06-21 06:50 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **57.77777777777778**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-2360-develop-AutoRecovery&id=tapdata

2024-06-21 10:50 UTC, ply0011 requested changes

2024-06-21 10:50 UTC, ply0011 commented on iengine/api/src/test/java/io/tapdata/inspect/AutoRecoveryTest.java
> +            AutoRecovery ignore2 = AutoRecovery.init(taskId)
这块可以用更好的断言
DuplicateAutoRecoveryException e = assertThrows(DuplicateAutoRecoveryException.class, ()->AutoRecovery.init(taskId));
assertEquals("xxx", e.getMessage());
类似这样写，单测不建议用try catch，可能会把一些错误掩盖

2024-06-21 11:06 UTC, HarsenLin commented on iengine/api/src/test/java/io/tapdata/inspect/AutoRecoveryTest.java
> +            AutoRecovery ignore2 = AutoRecovery.init(taskId)
很好的建议，已调整

2024-06-24 02:47 UTC, ply0011 approved these changes

2024-06-24 02:47 UTC, merged