TAP-2713 fix JoinProcessor dateType error
tapdata/tapdata pull request #2025
Opened 2024-06-21 08:03 UTC by weiliang110100

2024-06-21 11:16 UTC, ply0011 requested changes

2024-06-21 11:16 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/processor/join/HazelcastJoinProcessor.java
> +				return ((DateTime) value).toDate();
最好用toInstant()

2024-06-26 03:25 UTC, weiliang110100 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/processor/join/HazelcastJoinProcessor.java
> +				return ((DateTime) value).toDate();
使用toDate()无时区问题

2024-06-26 08:54 UTC, ply0011 approved these changes

2024-06-26 08:55 UTC, merged