TAP-3438 save task promp
tapdata/tapdata pull request #2079
Opened 2024-07-09 03:08 UTC by ningmeng777

2024-07-09 07:33 UTC, ply0011 requested changes

2024-07-09 07:33 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/TaskServiceImpl.java
> +        if (taskDto.getType().contains("cdc")) {
优化一下，减少同一个连接id的查询次数

2024-07-09 08:13 UTC, ningmeng777 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/TaskServiceImpl.java
> +        if (taskDto.getType().contains("cdc")) {
OK

2024-07-10 02:57 UTC, ply0011 approved these changes

2024-07-10 02:57 UTC, merged