Tap 1134 user requirements check details page check exception result details must be able to download
tapdata/tapdata pull request #2084
Opened 2024-07-09 11:18 UTC by ningmeng777

2024-07-09 12:25 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-1134-User-Requirements-Check-details-page-check-exception-result-details-must-be-able-to-download&id=tapdata

2024-07-10 03:14 UTC, ply0011 approved these changes

2024-07-10 03:16 UTC, ply0011 approved these changes

2024-07-10 03:18 UTC, ply0011 requested changes

2024-07-10 03:18 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/inspect/controller/InspectDetailsController.java
> +            log.error("Export inspectDetails  failed", e);
是否应该将异常抛出给前端，显示在界面

2024-07-10 03:22 UTC, ningmeng777 commented on manager/tm/src/main/java/com/tapdata/tm/inspect/controller/InspectDetailsController.java
> +            log.error("Export inspectDetails  failed", e);
OK 我修改下

2024-07-10 07:03 UTC, ply0011 approved these changes

2024-07-10 07:03 UTC, merged