fix: standard js node process before
tapdata/tapdata pull request #2099
Opened 2024-07-12 04:20 UTC by mnianqi

2024-07-12 06:27 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3457-standardJS-process-before&id=tapdata

2024-07-12 08:39 UTC, ply0011 requested changes
1. delete事件可能会运行两次js，浪费资源
2. before数据经过js，没有接收返回值

2024-07-12 11:10 UTC, ply0011 requested changes

2024-07-12 11:10 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/processor/HazelcastJavaScriptProcessorNode.java
> +			if (standard && null != context.get(BEFORE) && !context.get(BEFORE).equals(afterMapInRecord)) {
根据事件类型判断

2024-07-12 11:10 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/processor/HazelcastJavaScriptProcessorNode.java
> +				flushBeforeIfNeed(processedBefore, returnTapEvent, recordMap);
1. 这里放进去的不应该是recordMap
2. 这里before也是个List，需要跟after一样的处理

2024-07-15 08:35 UTC, ply0011 requested changes

2024-07-15 08:35 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/processor/HazelcastJavaScriptProcessorNode.java
> +			}
```
	if (TapUpdateRecordEvent.TYPE == tapEvent.getType() && MapUtils.isNotEmpty(before)) {
		scriptInvokeBeforeResult.set(engine.invokeFunction(ScriptUtil.FUNCTION_NAME, before));
	}
```

2024-07-15 08:35 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/processor/HazelcastJavaScriptProcessorNode.java
> +			Object beforeMap = ((List<?>) processedBefore).get(index);
兼容一下超出下标的场景

2024-07-15 12:27 UTC, ply0011 approved these changes

2024-07-15 12:27 UTC, merged