feat: TAP-1315 You can configure a proxy server when configuring the …
tapdata/tapdata pull request #2157
Opened 2024-07-31 02:59 UTC by mnianqi

…SMTP service

2024-07-31 07:21 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-1315-proxy-SMTP-service&id=tapdata

2024-07-31 10:40 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-1315-proxy-SMTP-service&id=tapdata

2024-08-01 02:44 UTC, ply0011 requested changes

2024-08-01 02:44 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/common/BaseEmailExecutor.java
> +				if (StringUtils.isNotBlank(proxyHost) && StringUtils.isNotBlank(proxyPort)) {
尝试减少重复代码

2024-08-01 02:44 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/Settings/service/SettingsServiceImpl.java
> +        if (StringUtils.isNotBlank(proxyHost) && StringUtils.isNotBlank(proxyPort)) {
尝试减少判断分支

2024-08-01 02:44 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/Settings/service/SettingsServiceImpl.java
> +        if (StringUtils.isNotBlank(proxyHost) && StringUtils.isNotBlank(proxyPort)) {
尝试减少判断分支

2024-08-01 11:19 UTC, ply0011 approved these changes

2024-08-01 11:19 UTC, merged