TAP-4176:fix unwind error
tapdata/tapdata pull request #2169
Opened 2024-08-05 04:05 UTC by weiliang110100

2024-08-05 04:25 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix_TAP-4176_unwind_error&id=tapdata

2024-08-05 08:33 UTC, ply0011 requested changes

2024-08-05 08:33 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/processor/HazelcastProcessorBaseNode.java
> +				BatchEventWrapper finalBatchEventWrapper = new BatchEventWrapper(event,batchEventWrapper.getProcessAspect());
丢失了原先batchEventWrapper的一些属性

2024-08-05 08:56 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **66.66666666666667**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix_TAP-4176_unwind_error&id=tapdata

2024-08-07 03:17 UTC, ply0011 requested changes
1. 根据处理节点实现，来控制是否需要clone
2. 处理与分支TAP-4266的冲突

2024-08-07 06:33 UTC, ply0011 approved these changes

2024-08-07 06:33 UTC, merged