feat: TAP-2415 License management needs to be able to control accordi…
tapdata/tapdata pull request #2232
Opened 2024-09-02 02:33 UTC by mnianqi

…ng to data source

2024-09-02 06:08 UTC, HarsenLin commented on manager/tm/src/main/java/com/tapdata/tm/ds/service/impl/DataSourceServiceImpl.java
Whether to change line 1941 to 'options.getDatasourceInstanceInfo()'

2024-09-02 06:48 UTC, HarsenLin requested changes
Whether to change line 1941 to 'options.getDatasourceInstanceInfo()'

2024-09-02 06:48 UTC, HarsenLin commented on manager/tm/src/main/java/com/tapdata/tm/ds/service/impl/DataSourceServiceImpl.java
Whether to change line 1941 to 'options.getDatasourceInstanceInfo()'

2024-09-02 11:44 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **60.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2415&id=tapdata

2024-09-04 07:52 UTC, ply0011 approved these changes

2024-09-04 08:02 UTC, HarsenLin approved these changes

2024-09-04 08:02 UTC, merged