fix: TAP-4584 Real Time Data Hub FDM Table status error
tapdata/tapdata pull request #2262
Opened 2024-09-25 11:18 UTC by mnianqi

2024-09-26 02:50 UTC, ply0011 requested changes
这个色入

2024-09-26 02:50 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/metadatainstance/service/MetadataInstancesServiceImpl.java
> +                .and(TASK_ID).exists(false)
这个方法，controller有接口，注释写的是“校验物理表是否存在"，这样改会导致接口能力变化

2024-09-26 02:50 UTC, ply0011 commented on manager/tm/src/main/java/com/tapdata/tm/task/service/impl/LdpServiceImpl.java
> +									boolean exist = metadataInstancesService.checkTableExist(lastConnectionId, tableName, user);
这里模型状态，应该根据任务状态来判断
- complete
- running但是已经进入增量

这两种状态应该都可以认为模型是done了，但是确认一下，有done这个状态枚举么？旧代码中，只看到running和noRunning，不知道是不是我遗漏了什么，还是done是新加的状态？

2024-09-29 06:42 UTC, mnianqi commented on manager/tm/src/main/java/com/tapdata/tm/task/service/impl/LdpServiceImpl.java
> +									boolean exist = metadataInstancesService.checkTableExist(lastConnectionId, tableName, user);
done为新加状态，表示该表已存在

2024-09-29 06:45 UTC, mnianqi commented on manager/tm/src/main/java/com/tapdata/tm/metadatainstance/service/MetadataInstancesServiceImpl.java
> +                .and(TASK_ID).exists(false)
source为job_analyze的条件不会影响物理表是否存在的判断

2024-09-29 09:50 UTC, merged