Tap 5239 add catch data feature
tapdata/tapdata pull request #2371
Opened 2024-11-22 09:09 UTC by openlg

2024-11-25 05:04 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **58.4**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **3.15789**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5239-feature-debug-data&id=tapdata

2024-11-25 07:46 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.2**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **3.15789**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5239-feature-debug-data&id=tapdata

2024-12-02 04:11 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **60.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5239-feature-debug-data&id=tapdata

2024-12-04 07:53 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **71.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5239-feature-debug-data&id=tapdata

2024-12-04 08:22 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **70.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5239-feature-debug-data&id=tapdata

2024-12-04 09:15 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **67.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5239-feature-debug-data&id=tapdata

2024-12-04 11:21 UTC, ply0011 requested changes

2024-12-04 11:21 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/flow/engine/V2/node/hazelcast/HazelcastBaseNode.java
> +		List<Map<String, Object>> data = new ArrayList<>(2);
使用TapEventUtil获取after或者before

2024-12-04 11:21 UTC, ply0011 commented on iengine/modules/observable-module/src/main/java/io/tapdata/observable/logging/ObsLoggerFactory.java
> +		//scheduleExecutorService.scheduleAtFixedRate(this::renewTaskLogSetting, 0L, PERIOD_SECOND, TimeUnit.SECONDS);
不需要的代码删除

2024-12-04 11:21 UTC, ply0011 commented on iengine/modules/observable-module/src/main/java/io/tapdata/observable/logging/ObsLoggerFactory.java
> +	@Deprecated
可以删掉了

2024-12-05 02:29 UTC, closed without merging