feat(iengine): TAP-3360 engine can start without mongodb config
tapdata/tapdata pull request #2384
Opened 2024-12-04 06:54 UTC by mnianqi

2024-12-04 10:54 UTC, ply0011 requested changes

2024-12-04 10:54 UTC, ply0011 commented on iengine/iengine-app/src/main/java/io/tapdata/Schedule/ConnectorManager.java
> +	protected String buildAccesscode() {
io.tapdata.Schedule.ConnectorManager#initVariable应该已经初始化了这个变量

2024-12-05 04:20 UTC, xbsura commented
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **66.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3360&id=tapdata

2024-12-05 06:32 UTC, ply0011 approved these changes

2024-12-05 06:32 UTC, merged